name: Translate Monitored Documents on Update

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.md'

permissions:
  contents: write
  pull-requests: write

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyyaml openai

      - name: Identify changed monitored files
        id: detect
        run: |
          echo "🔍 Loading translation list..."
          python .github/scripts/identify_changed_files.py > changed_files.txt
          echo "✅ Done. Changed monitored files:"
          cat changed_files.txt

      - name: Translate changed files
        run: |
          echo "⌛ Translating, please wait..."
          python .github/scripts/translate_changed_files.py changed_files.txt > translated_files.txt
          echo "✅ Done. Translated files:"
          cat translated_files.txt
        env:
          API_KEY: ${{ secrets.OPENAI_API_KEY }}


      # https://github.com/ecnusse/Kea/blob/main/.github/workflows/update_translation.yml
      - name: Commit and push changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git switch main
          
          xargs -a translated_files.txt git add

          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-translate updated documentation"
            git pull --rebase
            git push origin main
          else
            echo "No changes to commit."
          fi
